#:kivy 2.1.0
#:import rgba kivy.utils.get_color_from_hex


    

<SmartSystem>:
   # camera: face_recognition_camera
    key_panel: m_key_panel

    MDBoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        adaptive_size: True

        #KivyCamera:
           # id: face_recognition_camera
           
        
        KeyPanel:
            id:m_key_panel
            
            

                  


    

   


