#:kivy 2.1.0
<KivyCamera>:
   BoxLayout:
      orientation: 'horizontal'
      size: root.width, root.height
   Button:
      id: KivyCamera_verify_btn
      text: 'Verify'
      size: root.width , 30
      pos: 0, 0
      background_color: .0, .58, .38, .8



   ProgressBar:
      id: KivyCamera_vertical_progress_bar
      orientation: 'vertical'
      value: 0
      min: 0
      max: 100
      size: root.width /2 ,10
      pos: root.width/4, root.height /2









